name: PR Infrastructure Plan

on:
  workflow_dispatch:
    inputs:
      use_private_agent:
        description: Use a private agent to deploy the built artifact.
        type: boolean
        required: false
        default: false
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/infra-**.yaml"
      - "infra/resources/**"

jobs:
  infra_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@20d0f058e2ec917e2d00ad1732f20c55b0cc2ef5
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: ${{ github.event_name != 'workflow_dispatch' && false }}
