name: Plan (resources)

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/infra-.yaml"
      - "infra/resources/"

jobs:
  set_env_vars:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.set_env_vars.outputs.env_vars }}
    steps:
      - name: Set Environment Variables
        id: set_env_vars
        run: |
          echo "env_vars=ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}\nARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}\nARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_OUTPUT

  infra_review:
    needs: set_env_vars
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: PR Prod ItalyNorth
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: false
      override_github_environment: infra-prod
      env_vars: ${{ needs.set_env_vars.outputs.env_vars }}
